/*++

Module Name:

    lamparray.h

Abstract:

    The HID LampArray wire format: the report descriptor we hand to VHF, and the six feature reports the host
    exchanges with us. Composed per "Lighting And Illumination Page (0x59)" of HID Usage Tables 1.4
    (https://www.usb.org/sites/default/files/hut1_4.pdf).

    The descriptor below is Microsoft's canonical one — generated by their WaratahCmd tool and published in
    github.com/microsoft/ArduinoHidForWindows (MIT licence, Copyright (c) Microsoft Corporation) — reused
    verbatim on purpose: it is what Windows' own LampArray sample devices report, so we are testing against the
    same bytes the OS is known to accept. The report structs mirror the same project's LampArrayReports.h with
    Windows types.

    Note that the descriptor is COMPLETELY STATIC: lamp count, geometry and kind travel in the *attributes
    report*, not in the descriptor. That is why the driver never has to regenerate it when the app pushes a new
    layout, and why the layout can change without touching this file.

--*/

#pragma once

//
// Feature report ids, and the "update complete" flag the host sets on the last report of a batch.
//
#define AHLA_REPORT_ATTRIBUTES          1   // GET:  device-wide attributes (lamp count, bounding box, kind)
#define AHLA_REPORT_ATTR_REQUEST        2   // SET:  select which lamp the next attributes GET describes
#define AHLA_REPORT_ATTR_RESPONSE       3   // GET:  the selected lamp's attributes (then auto-advances)
#define AHLA_REPORT_MULTI_UPDATE        4   // SET:  up to 8 (lamp id, colour) pairs
#define AHLA_REPORT_RANGE_UPDATE        5   // SET:  one colour for a contiguous id range
#define AHLA_REPORT_CONTROL             6   // SET:  autonomous mode on/off (host takes/releases the surface)

#define AHLA_MULTI_UPDATE_LAMP_COUNT    8
#define AHLA_UPDATE_FLAG_COMPLETE       1

#include <pshpack1.h>

typedef struct _AHLA_ATTRIBUTES_REPORT
{
    UCHAR  ReportId;
    USHORT LampCount;
    ULONG  BoundingBoxWidthInMicrometers;
    ULONG  BoundingBoxHeightInMicrometers;
    ULONG  BoundingBoxDepthInMicrometers;
    ULONG  LampArrayKind;
    ULONG  MinUpdateIntervalInMicroseconds;
} AHLA_ATTRIBUTES_REPORT;

typedef struct _AHLA_ATTR_REQUEST_REPORT
{
    UCHAR  ReportId;
    USHORT LampId;
} AHLA_ATTR_REQUEST_REPORT;

typedef struct _AHLA_ATTR_RESPONSE_REPORT
{
    UCHAR  ReportId;
    USHORT LampId;
    ULONG  PositionXInMicrometers;
    ULONG  PositionYInMicrometers;
    ULONG  PositionZInMicrometers;
    ULONG  UpdateLatencyInMicroseconds;
    ULONG  LampPurposes;
    UCHAR  RedLevelCount;
    UCHAR  GreenLevelCount;
    UCHAR  BlueLevelCount;
    UCHAR  IntensityLevelCount;
    UCHAR  IsProgrammable;
    UCHAR  InputBinding;
} AHLA_ATTR_RESPONSE_REPORT;

typedef struct _AHLA_HID_COLOR
{
    UCHAR RedChannel;
    UCHAR GreenChannel;
    UCHAR BlueChannel;
    UCHAR IntensityChannel;
} AHLA_HID_COLOR;

typedef struct _AHLA_MULTI_UPDATE_REPORT
{
    UCHAR          ReportId;
    UCHAR          LampCount;
    UCHAR          LampUpdateFlags;
    USHORT         LampIds[AHLA_MULTI_UPDATE_LAMP_COUNT];
    AHLA_HID_COLOR UpdateColors[AHLA_MULTI_UPDATE_LAMP_COUNT];
} AHLA_MULTI_UPDATE_REPORT;

typedef struct _AHLA_RANGE_UPDATE_REPORT
{
    UCHAR          ReportId;
    UCHAR          LampUpdateFlags;
    USHORT         LampIdStart;
    USHORT         LampIdEnd;
    AHLA_HID_COLOR UpdateColor;
} AHLA_RANGE_UPDATE_REPORT;

typedef struct _AHLA_CONTROL_REPORT
{
    UCHAR ReportId;
    UCHAR AutonomousMode;
} AHLA_CONTROL_REPORT;

#include <poppack.h>

//
// Report sizes the descriptor promises (payload + the leading report id byte). If one of these fires, the
// descriptor and the structs have drifted apart.
//
C_ASSERT(sizeof(AHLA_ATTRIBUTES_REPORT) == 1 + 22);
C_ASSERT(sizeof(AHLA_ATTR_REQUEST_REPORT) == 1 + 2);
C_ASSERT(sizeof(AHLA_ATTR_RESPONSE_REPORT) == 1 + 28);
C_ASSERT(sizeof(AHLA_MULTI_UPDATE_REPORT) == 1 + 50);
C_ASSERT(sizeof(AHLA_RANGE_UPDATE_REPORT) == 1 + 9);
C_ASSERT(sizeof(AHLA_CONTROL_REPORT) == 1 + 1);

//
// Permits describing a LampArray with up to 65535 lamps. 292 bytes.
//
// From github.com/microsoft/ArduinoHidForWindows (MIT, Copyright (c) Microsoft Corporation),
// AUTO-GENERATED there by WaratahCmd.exe (github.com/microsoft/hidtools) against HID Usage Tables 1.4.
//
// +----------+---------+-------------------+
// | ReportId | Kind    | ReportSizeInBytes |
// +----------+---------+-------------------+
// |        1 | Feature |                22 |
// |        2 | Feature |                 2 |
// |        3 | Feature |                28 |
// |        4 | Feature |                50 |
// |        5 | Feature |                 9 |
// |        6 | Feature |                 1 |
// +----------+---------+-------------------+
//
static const UCHAR AhlaReportDescriptor[] =
{
    0x05, 0x59,                      // UsagePage(Lighting And Illumination[0x0059])
    0x09, 0x01,                      // UsageId(LampArray[0x0001])
    0xA1, 0x01,                      // Collection(Application)
    0x85, 0x01,                      //     ReportId(1)
    0x09, 0x02,                      //     UsageId(LampArrayAttributesReport[0x0002])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x03,                      //         UsageId(LampCount[0x0003])
    0x15, 0x00,                      //         LogicalMinimum(0)
    0x27, 0xFF, 0xFF, 0x00, 0x00,    //         LogicalMaximum(65,535)
    0x95, 0x01,                      //         ReportCount(1)
    0x75, 0x10,                      //         ReportSize(16)
    0xB1, 0x03,                      //         Feature(Constant, Variable, Absolute)
    0x09, 0x04,                      //         UsageId(BoundingBoxWidthInMicrometers[0x0004])
    0x09, 0x05,                      //         UsageId(BoundingBoxHeightInMicrometers[0x0005])
    0x09, 0x06,                      //         UsageId(BoundingBoxDepthInMicrometers[0x0006])
    0x09, 0x07,                      //         UsageId(LampArrayKind[0x0007])
    0x09, 0x08,                      //         UsageId(MinUpdateIntervalInMicroseconds[0x0008])
    0x27, 0xFF, 0xFF, 0xFF, 0x7F,    //         LogicalMaximum(2,147,483,647)
    0x95, 0x05,                      //         ReportCount(5)
    0x75, 0x20,                      //         ReportSize(32)
    0xB1, 0x03,                      //         Feature(Constant, Variable, Absolute)
    0xC0,                            //     EndCollection()
    0x85, 0x02,                      //     ReportId(2)
    0x09, 0x20,                      //     UsageId(LampAttributesRequestReport[0x0020])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x21,                      //         UsageId(LampId[0x0021])
    0x27, 0xFF, 0xFF, 0x00, 0x00,    //         LogicalMaximum(65,535)
    0x95, 0x01,                      //         ReportCount(1)
    0x75, 0x10,                      //         ReportSize(16)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0xC0,                            //     EndCollection()
    0x85, 0x03,                      //     ReportId(3)
    0x09, 0x22,                      //     UsageId(LampAttributesResponseReport[0x0022])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x21,                      //         UsageId(LampId[0x0021])
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0x09, 0x23,                      //         UsageId(PositionXInMicrometers[0x0023])
    0x09, 0x24,                      //         UsageId(PositionYInMicrometers[0x0024])
    0x09, 0x25,                      //         UsageId(PositionZInMicrometers[0x0025])
    0x09, 0x27,                      //         UsageId(UpdateLatencyInMicroseconds[0x0027])
    0x09, 0x26,                      //         UsageId(LampPurposes[0x0026])
    0x27, 0xFF, 0xFF, 0xFF, 0x7F,    //         LogicalMaximum(2,147,483,647)
    0x95, 0x05,                      //         ReportCount(5)
    0x75, 0x20,                      //         ReportSize(32)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0x09, 0x28,                      //         UsageId(RedLevelCount[0x0028])
    0x09, 0x29,                      //         UsageId(GreenLevelCount[0x0029])
    0x09, 0x2A,                      //         UsageId(BlueLevelCount[0x002A])
    0x09, 0x2B,                      //         UsageId(IntensityLevelCount[0x002B])
    0x09, 0x2C,                      //         UsageId(IsProgrammable[0x002C])
    0x09, 0x2D,                      //         UsageId(InputBinding[0x002D])
    0x26, 0xFF, 0x00,                //         LogicalMaximum(255)
    0x95, 0x06,                      //         ReportCount(6)
    0x75, 0x08,                      //         ReportSize(8)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0xC0,                            //     EndCollection()
    0x85, 0x04,                      //     ReportId(4)
    0x09, 0x50,                      //     UsageId(LampMultiUpdateReport[0x0050])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x03,                      //         UsageId(LampCount[0x0003])
    0x25, 0x08,                      //         LogicalMaximum(8)
    0x95, 0x01,                      //         ReportCount(1)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0x09, 0x55,                      //         UsageId(LampUpdateFlags[0x0055])
    0x25, 0x01,                      //         LogicalMaximum(1)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0x09, 0x21,                      //         UsageId(LampId[0x0021])
    0x27, 0xFF, 0xFF, 0x00, 0x00,    //         LogicalMaximum(65,535)
    0x95, 0x08,                      //         ReportCount(8)
    0x75, 0x10,                      //         ReportSize(16)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x26, 0xFF, 0x00,                //         LogicalMaximum(255)
    0x95, 0x20,                      //         ReportCount(32)
    0x75, 0x08,                      //         ReportSize(8)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0xC0,                            //     EndCollection()
    0x85, 0x05,                      //     ReportId(5)
    0x09, 0x60,                      //     UsageId(LampRangeUpdateReport[0x0060])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x55,                      //         UsageId(LampUpdateFlags[0x0055])
    0x25, 0x01,                      //         LogicalMaximum(1)
    0x95, 0x01,                      //         ReportCount(1)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0x09, 0x61,                      //         UsageId(LampIdStart[0x0061])
    0x09, 0x62,                      //         UsageId(LampIdEnd[0x0062])
    0x27, 0xFF, 0xFF, 0x00, 0x00,    //         LogicalMaximum(65,535)
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x10,                      //         ReportSize(16)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0x09, 0x51,                      //         UsageId(RedUpdateChannel[0x0051])
    0x09, 0x52,                      //         UsageId(GreenUpdateChannel[0x0052])
    0x09, 0x53,                      //         UsageId(BlueUpdateChannel[0x0053])
    0x09, 0x54,                      //         UsageId(IntensityUpdateChannel[0x0054])
    0x26, 0xFF, 0x00,                //         LogicalMaximum(255)
    0x95, 0x04,                      //         ReportCount(4)
    0x75, 0x08,                      //         ReportSize(8)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0xC0,                            //     EndCollection()
    0x85, 0x06,                      //     ReportId(6)
    0x09, 0x70,                      //     UsageId(LampArrayControlReport[0x0070])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x71,                      //         UsageId(AutonomousMode[0x0071])
    0x25, 0x01,                      //         LogicalMaximum(1)
    0x95, 0x01,                      //         ReportCount(1)
    0xB1, 0x02,                      //         Feature(Data, Variable, Absolute)
    0xC0,                            //     EndCollection()
    0xC0,                            // EndCollection()
};

C_ASSERT(sizeof(AhlaReportDescriptor) == 292);
